apiVersion: apps/v1
kind: Deployment
metadata:
  name: buzz
spec:
  replicas: 10
  selector:
    matchLabels:
      app: buzz
  template:
    metadata:
      labels:
        app: buzz
    spec:
      containers:
      - name: buzz
        image: robclenshaw/fizzbuzz-worker
        env:
          - name: DIVISOR
            value: "5"
          - name: OUTPUT_PHRASE
            value: "Buzz"
        livenessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1