apiVersion: apps/v1
kind: Deployment
metadata:
  name: fizzbuzz
spec:
  selector:
    matchLabels:
      app: fizzbuzz
  template:
    metadata:
      labels:
        app: fizzbuzz
    spec:
      containers:
      - name: fizzbuzz
        image: robclenshaw/fizzbuzz