apiVersion: apps/v1
kind: Deployment
metadata:
  name: fizz
spec:
  replicas: 10
  selector:
    matchLabels:
      app: fizz
  template:
    metadata:
      labels:
        app: fizz
    spec:
      containers:
      - name: fizz
        image: rclenshaw.azurecr.io/fizzbuzz-worker
        env:
          - name: DIVISOR
            value: "3"
          - name: OUTPUT_PHRASE
            value: "Fizz"
        livenessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 1
      imagePullSecrets:
      - name: acr